# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: caligrafo 0.1.8 ruby lib

Gem::Specification.new do |s|
  s.name = "caligrafo"
  s.version = "0.1.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Lucas de Castro"]
  s.date = "2016-11-10"
  s.description = "DSL para gera\u{e7}\u{e3}o de arquivos texto."
  s.email = "castro.lucas@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "caligrafo.gemspec",
    "lib/caligrafo.rb",
    "lib/caligrafo/converter.rb",
    "lib/caligrafo/descriptor.rb",
    "lib/caligrafo/fixnum.rb",
    "lib/caligrafo/reader.rb",
    "lib/caligrafo/writer.rb",
    "test/caligrafo_test.rb",
    "test/example.rb",
    "test/example.txt",
    "test/formatador_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/lucasdecastro/caligrafo"
  s.rubygems_version = "2.5.1"
  s.summary = "DSL para gera\u{e7}\u{e3}o de arquivos texto."
end

