# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{caligrafo}
  s.version = "0.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lucas de Castro"]
  s.date = %q{2010-06-17}
  s.description = %q{DSL para geração de arquivos texto.}
  s.email = %q{castro.lucas@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "caligrafo.gemspec",
     "lib/caligrafo.rb",
     "lib/caligrafo/converter.rb",
     "lib/caligrafo/descriptor.rb",
     "lib/caligrafo/fixnum.rb",
     "lib/caligrafo/reader.rb",
     "lib/caligrafo/writer.rb",
     "test/caligrafo_test.rb",
     "test/example.rb",
     "test/example.txt",
     "test/formatador_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/lucasdecastro/caligrafo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{DSL para geração de arquivos texto.}
  s.test_files = [
    "test/test_helper.rb",
     "test/caligrafo_test.rb",
     "test/formatador_test.rb",
     "test/example.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
